name: "📃 Docs"
description: "문서 작성 및 수정 (README.md 등)"
labels: ["📃 Docs"]
body:
  - type: textarea
    attributes:
      label: 📄 설명
      description: 추가할 내용을 간단하게 작성해 주세요.
      placeholder: 고양이는 귀여워요!
    validations:
      required: true
  - type: textarea
    attributes:
      label: ✅ 작업할 내용
      description: 할 일을 체크박스 형태로 작성해주세요.
      placeholder: 최대한 세분화 해서 적어주세요!
    validations:
      required: true
  - type: textarea
    attributes:
      label: 🙋🏻 참고 자료
      description: 참고 자료가 있다면 작성해 주세요.